### ISSUE TITLE
Stale project

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/DesignClubWebsite#4]
This project is inactive for the last 10 months. If design club is willing to work on this, please reply here before 1st January 2017; failing to which, this repository will be deleted.

**Comment by geekyJock8** [comment]
@Monal5031 was supposed to look at this!

**Comment by Monal5031** [comment]
@geekyJock8 as per the last time we discussed on asana, the layout was to be decided. Please remind me if I am missing something 😕

**Comment by Monal5031** [comment]
@singhpratyush Sir we are forming a team of some Coding Club member and some Design Club members to complete this project. We'll be starting the work asap. 😄

**Comment by singhpratyush** [comment]
@Monal5031 @geekyJock8: Great to hear that. Hope this turns out to be a great project. Cheers!
